<?php 
/////////////////////
$system_language="ar";
/////////////////////
if(!$_SESSION['lang']){$_SESSION['lang']=$system_language;}

$cr_lang=$_SESSION['lang'];
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////// User Control Panel //////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////// A   charge_card.php   ///////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//a1
if($cr_lang=="ar"){$lang_a_1="‘Ќд Ќ”«»я";}
if($cr_lang=="en"){$lang_a_1="Charge Account";}
//a2
if($cr_lang=="ar"){$lang_a_2="«б—∆н”н…";}
if($cr_lang=="en"){$lang_a_2="Home";}
//a3
if($cr_lang=="ar"){$lang_a_3="«б—’нѕ";}
if($cr_lang=="en"){$lang_a_3="Creadit";}
//a4
if($cr_lang=="ar"){$lang_a_4="‘Ќд Ќ”«»я";}
if($cr_lang=="en"){$lang_a_4="Charge Account";}
//a5
if($cr_lang=="ar"){$lang_a_5=" г «б‘Ќд »дћ«Ќ";}
if($cr_lang=="en"){$lang_a_5="Charging completed successfully";}
//a6
if($cr_lang=="ar"){$lang_a_6="ёнг… «бя«— ";}
if($cr_lang=="en"){$lang_a_6="value of the card";}
//a7
if($cr_lang=="ar"){$lang_a_7="—’нѕя ё»б «б‘Ќд";}
if($cr_lang=="en"){$lang_a_7="Balance before charging";}
//a8
if($cr_lang=="ar"){$lang_a_8="—’нѕя «бЌ«бн »Џѕ «б‘Ќд";}
if($cr_lang=="en"){$lang_a_8="Your current balance after charging";}
//a9
if($cr_lang=="ar"){$lang_a_9="ёг »«б÷џЎ ед« б‘—«Ѕ «б»«ё… «бгд«”»… «бня";}
if($cr_lang=="en"){$lang_a_9="Click here to buy internet package";}
//a10
if($cr_lang=="ar"){$lang_a_10="б  гяд гд «бѕќжб Џбм «б≈д —д ";}
if($cr_lang=="en"){$lang_a_10="to be able to access the internet";}
//a11
if($cr_lang=="ar"){$lang_a_11="ЏЁж« ... Ќ«жб Ём жё  б«Ќё";}
if($cr_lang=="en"){$lang_a_11="Sorry ...Try again later.";}
//a12
if($cr_lang=="ar"){$lang_a_12="ЏЁж« ... —ёг я«—  ќ«Ў∆";}
if($cr_lang=="en"){$lang_a_12="Sorry ... card number wrong.";}
//a13
if($cr_lang=="ar"){$lang_a_13="гд Ё÷бя √ѕќб —ёг я«—  «б‘Ќд";}
if($cr_lang=="en"){$lang_a_13="Please enter the card number";}
//a14
if($cr_lang=="ar"){$lang_a_14="ЏЁж« ... бёѕ ≈” дЁ“  Џѕѕ «бгЌ«жб«  «бгёѕ—… бя";}
if($cr_lang=="en"){$lang_a_14="Sorry ... you have exhausted the estimated number of attempts";}
//a15
if($cr_lang=="ar"){$lang_a_15="‘Ќд";}
if($cr_lang=="en"){$lang_a_15="Charge";}
//a16
if($cr_lang=="ar"){$lang_a_16="";}
if($cr_lang=="en"){$lang_a_16="";}
//a17
if($cr_lang=="ar"){$lang_a_17="";}
if($cr_lang=="en"){$lang_a_17="";}
//a18
if($cr_lang=="ar"){$lang_a_18="";}
if($cr_lang=="en"){$lang_a_18="";}
//a19
if($cr_lang=="ar"){$lang_a_19="";}
if($cr_lang=="en"){$lang_a_19="";}
//a20
if($cr_lang=="ar"){$lang_a_20="";}
if($cr_lang=="en"){$lang_a_20="";}
//a21
if($cr_lang=="ar"){$lang_a_21="";}
if($cr_lang=="en"){$lang_a_21="";}
//a22
if($cr_lang=="ar"){$lang_a_22="";}
if($cr_lang=="en"){$lang_a_22="";}
//a23
if($cr_lang=="ar"){$lang_a_23="";}
if($cr_lang=="en"){$lang_a_23="";}
//a24
if($cr_lang=="ar"){$lang_a_24="";}
if($cr_lang=="en"){$lang_a_24="";}
//a25
if($cr_lang=="ar"){$lang_a_25="";}
if($cr_lang=="en"){$lang_a_25="";}
//a26
if($cr_lang=="ar"){$lang_a_26="";}
if($cr_lang=="en"){$lang_a_26="";}
//a27
if($cr_lang=="ar"){$lang_a_27="";}
if($cr_lang=="en"){$lang_a_27="";}
//a28
if($cr_lang=="ar"){$lang_a_28="";}
if($cr_lang=="en"){$lang_a_28="";}
//a29
if($cr_lang=="ar"){$lang_a_29="";}
if($cr_lang=="en"){$lang_a_29="";}
//a30
if($cr_lang=="ar"){$lang_a_30="";}
if($cr_lang=="en"){$lang_a_30="";}
//a31
if($cr_lang=="ar"){$lang_a_31="";}
if($cr_lang=="en"){$lang_a_31="";}
//a32
if($cr_lang=="ar"){$lang_a_32="";}
if($cr_lang=="en"){$lang_a_32="";}
//a33
if($cr_lang=="ar"){$lang_a_33="";}
if($cr_lang=="en"){$lang_a_33="";}
//a34
if($cr_lang=="ar"){$lang_a_34="";}
if($cr_lang=="en"){$lang_a_34="";}
//a35
if($cr_lang=="ar"){$lang_a_35="";}
if($cr_lang=="en"){$lang_a_35="";}
//a36
if($cr_lang=="ar"){$lang_a_36="";}
if($cr_lang=="en"){$lang_a_36="";}
//a37
if($cr_lang=="ar"){$lang_a_37="";}
if($cr_lang=="en"){$lang_a_37="";}
//a38
if($cr_lang=="ar"){$lang_a_38="";}
if($cr_lang=="en"){$lang_a_38="";}
//a39
if($cr_lang=="ar"){$lang_a_39="";}
if($cr_lang=="en"){$lang_a_39="";}
//a40
if($cr_lang=="ar"){$lang_a_40="";}
if($cr_lang=="en"){$lang_a_40="";}
//a41
if($cr_lang=="ar"){$lang_a_41="";}
if($cr_lang=="en"){$lang_a_41="";}
//a42
if($cr_lang=="ar"){$lang_a_42="";}
if($cr_lang=="en"){$lang_a_42="";}
//a43
if($cr_lang=="ar"){$lang_a_43="";}
if($cr_lang=="en"){$lang_a_43="";}
//a44
if($cr_lang=="ar"){$lang_a_44="";}
if($cr_lang=="en"){$lang_a_44="";}
//a45
if($cr_lang=="ar"){$lang_a_45="";}
if($cr_lang=="en"){$lang_a_45="";}
//a46
if($cr_lang=="ar"){$lang_a_46="";}
if($cr_lang=="en"){$lang_a_46="";}
//a47
if($cr_lang=="ar"){$lang_a_47="";}
if($cr_lang=="en"){$lang_a_47="";}
//a48
if($cr_lang=="ar"){$lang_a_48="";}
if($cr_lang=="en"){$lang_a_48="";}
//a49
if($cr_lang=="ar"){$lang_a_49="";}
if($cr_lang=="en"){$lang_a_49="";}
//a50
if($cr_lang=="ar"){$lang_a_50="";}
if($cr_lang=="en"){$lang_a_50="";}
//a51
if($cr_lang=="ar"){$lang_a_51="";}
if($cr_lang=="en"){$lang_a_51="";}
//a52
if($cr_lang=="ar"){$lang_a_52="";}
if($cr_lang=="en"){$lang_a_52="";}
//a53
if($cr_lang=="ar"){$lang_a_53="";}
if($cr_lang=="en"){$lang_a_53="";}
//a54
if($cr_lang=="ar"){$lang_a_54="";}
if($cr_lang=="en"){$lang_a_54="";}
//a55
if($cr_lang=="ar"){$lang_a_55="";}
if($cr_lang=="en"){$lang_a_55="";}
//a56
if($cr_lang=="ar"){$lang_a_56="";}
if($cr_lang=="en"){$lang_a_56="";}
//a57
if($cr_lang=="ar"){$lang_a_57="";}
if($cr_lang=="en"){$lang_a_57="";}
//a58
if($cr_lang=="ar"){$lang_a_58="";}
if($cr_lang=="en"){$lang_a_58="";}
//a59
if($cr_lang=="ar"){$lang_a_59="";}
if($cr_lang=="en"){$lang_a_59="";}
//a60
if($cr_lang=="ar"){$lang_a_60="";}
if($cr_lang=="en"){$lang_a_60="";}
//a61
if($cr_lang=="ar"){$lang_a_61="";}
if($cr_lang=="en"){$lang_a_61="";}
//a62
if($cr_lang=="ar"){$lang_a_62="";}
if($cr_lang=="en"){$lang_a_62="";}
//a63
if($cr_lang=="ar"){$lang_a_63="";}
if($cr_lang=="en"){$lang_a_63="";}
//a64
if($cr_lang=="ar"){$lang_a_64="";}
if($cr_lang=="en"){$lang_a_64="";}
//a65
if($cr_lang=="ar"){$lang_a_65="";}
if($cr_lang=="en"){$lang_a_65="";}
//a66
if($cr_lang=="ar"){$lang_a_66="";}
if($cr_lang=="en"){$lang_a_66="";}
//a67
if($cr_lang=="ar"){$lang_a_67="";}
if($cr_lang=="en"){$lang_a_67="";}
//a68
if($cr_lang=="ar"){$lang_a_68="";}
if($cr_lang=="en"){$lang_a_68="";}
//a69
if($cr_lang=="ar"){$lang_a_69="";}
if($cr_lang=="en"){$lang_a_69="";}
//a70
if($cr_lang=="ar"){$lang_a_70="";}
if($cr_lang=="en"){$lang_a_70="";}
//a71
if($cr_lang=="ar"){$lang_a_71="";}
if($cr_lang=="en"){$lang_a_71="";}
//a72
if($cr_lang=="ar"){$lang_a_72="";}
if($cr_lang=="en"){$lang_a_72="";}
//a73
if($cr_lang=="ar"){$lang_a_73="";}
if($cr_lang=="en"){$lang_a_73="";}
//a74
if($cr_lang=="ar"){$lang_a_74="";}
if($cr_lang=="en"){$lang_a_74="";}
//a75
if($cr_lang=="ar"){$lang_a_75="";}
if($cr_lang=="en"){$lang_a_75="";}
//a76
if($cr_lang=="ar"){$lang_a_76="";}
if($cr_lang=="en"){$lang_a_76="";}
//a77
if($cr_lang=="ar"){$lang_a_77="";}
if($cr_lang=="en"){$lang_a_77="";}
//a78
if($cr_lang=="ar"){$lang_a_78="";}
if($cr_lang=="en"){$lang_a_78="";}
//a79
if($cr_lang=="ar"){$lang_a_79="";}
if($cr_lang=="en"){$lang_a_79="";}
//a80
if($cr_lang=="ar"){$lang_a_80="";}
if($cr_lang=="en"){$lang_a_80="";}
//a81
if($cr_lang=="ar"){$lang_a_81="";}
if($cr_lang=="en"){$lang_a_81="";}
//a82
if($cr_lang=="ar"){$lang_a_82="";}
if($cr_lang=="en"){$lang_a_82="";}
//a83
if($cr_lang=="ar"){$lang_a_83="";}
if($cr_lang=="en"){$lang_a_83="";}
//a84
if($cr_lang=="ar"){$lang_a_84="";}
if($cr_lang=="en"){$lang_a_84="";}
//a85
if($cr_lang=="ar"){$lang_a_85="";}
if($cr_lang=="en"){$lang_a_85="";}
//a86
if($cr_lang=="ar"){$lang_a_86="";}
if($cr_lang=="en"){$lang_a_86="";}
//a87
if($cr_lang=="ar"){$lang_a_87="";}
if($cr_lang=="en"){$lang_a_87="";}
//a88
if($cr_lang=="ar"){$lang_a_88="";}
if($cr_lang=="en"){$lang_a_88="";}
//a89
if($cr_lang=="ar"){$lang_a_89="";}
if($cr_lang=="en"){$lang_a_89="";}
//a90
if($cr_lang=="ar"){$lang_a_90="";}
if($cr_lang=="en"){$lang_a_90="";}
//a91
if($cr_lang=="ar"){$lang_a_91="";}
if($cr_lang=="en"){$lang_a_91="";}
//a92
if($cr_lang=="ar"){$lang_a_92="";}
if($cr_lang=="en"){$lang_a_92="";}
//a93
if($cr_lang=="ar"){$lang_a_93="";}
if($cr_lang=="en"){$lang_a_93="";}
//a94
if($cr_lang=="ar"){$lang_a_94="";}
if($cr_lang=="en"){$lang_a_94="";}
//a95
if($cr_lang=="ar"){$lang_a_95="";}
if($cr_lang=="en"){$lang_a_95="";}
//a96
if($cr_lang=="ar"){$lang_a_96="";}
if($cr_lang=="en"){$lang_a_96="";}
//a97
if($cr_lang=="ar"){$lang_a_97="";}
if($cr_lang=="en"){$lang_a_97="";}
//a98
if($cr_lang=="ar"){$lang_a_98="";}
if($cr_lang=="en"){$lang_a_98="";}
//a99
if($cr_lang=="ar"){$lang_a_99="";}
if($cr_lang=="en"){$lang_a_99="";}
//a100
if($cr_lang=="ar"){$lang_a_100="";}
if($cr_lang=="en"){$lang_a_100="";}
/*
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////// B   charge_card.php   ///////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//b1
if($cr_lang=="ar"){$lang_b_1="";}
if($cr_lang=="en"){$lang_b_1="";}
//a2
if($cr_lang=="ar"){$lang_a_2="";}
if($cr_lang=="en"){$lang_a_2="";}
//a3
if($cr_lang=="ar"){$lang_a_3="";}
if($cr_lang=="en"){$lang_a_3="";}
//a4
if($cr_lang=="ar"){$lang_a_4="";}
if($cr_lang=="en"){$lang_a_4="";}
//a5
if($cr_lang=="ar"){$lang_a_5="";}
if($cr_lang=="en"){$lang_a_5="";}
//a6
if($cr_lang=="ar"){$lang_a_6="";}
if($cr_lang=="en"){$lang_a_6="";}
//a7
if($cr_lang=="ar"){$lang_a_7="";}
if($cr_lang=="en"){$lang_a_7="";}
//a8
if($cr_lang=="ar"){$lang_a_8="";}
if($cr_lang=="en"){$lang_a_8="";}
//a9
if($cr_lang=="ar"){$lang_a_9="";}
if($cr_lang=="en"){$lang_a_9="";}
//a10
if($cr_lang=="ar"){$lang_a_10="";}
if($cr_lang=="en"){$lang_a_10="";}
//a11
if($cr_lang=="ar"){$lang_a_11="";}
if($cr_lang=="en"){$lang_a_11="";}
//a12
if($cr_lang=="ar"){$lang_a_12="";}
if($cr_lang=="en"){$lang_a_12="";}
//a13
if($cr_lang=="ar"){$lang_a_13="";}
if($cr_lang=="en"){$lang_a_13="";}
//a14
if($cr_lang=="ar"){$lang_a_14="";}
if($cr_lang=="en"){$lang_a_14="";}
//a15
if($cr_lang=="ar"){$lang_a_15="";}
if($cr_lang=="en"){$lang_a_15="";}
//a16
if($cr_lang=="ar"){$lang_a_16="";}
if($cr_lang=="en"){$lang_a_16="";}
//a17
if($cr_lang=="ar"){$lang_a_17="";}
if($cr_lang=="en"){$lang_a_17="";}
//a18
if($cr_lang=="ar"){$lang_a_18="";}
if($cr_lang=="en"){$lang_a_18="";}
//a19
if($cr_lang=="ar"){$lang_a_19="";}
if($cr_lang=="en"){$lang_a_19="";}
//a20
if($cr_lang=="ar"){$lang_a_20="";}
if($cr_lang=="en"){$lang_a_20="";}
//a21
if($cr_lang=="ar"){$lang_a_21="";}
if($cr_lang=="en"){$lang_a_21="";}
//a22
if($cr_lang=="ar"){$lang_a_22="";}
if($cr_lang=="en"){$lang_a_22="";}
//a23
if($cr_lang=="ar"){$lang_a_23="";}
if($cr_lang=="en"){$lang_a_23="";}
//a24
if($cr_lang=="ar"){$lang_a_24="";}
if($cr_lang=="en"){$lang_a_24="";}
//a25
if($cr_lang=="ar"){$lang_a_25="";}
if($cr_lang=="en"){$lang_a_25="";}
//a26
if($cr_lang=="ar"){$lang_a_26="";}
if($cr_lang=="en"){$lang_a_26="";}
//a27
if($cr_lang=="ar"){$lang_a_27="";}
if($cr_lang=="en"){$lang_a_27="";}
//a28
if($cr_lang=="ar"){$lang_a_28="";}
if($cr_lang=="en"){$lang_a_28="";}
//a29
if($cr_lang=="ar"){$lang_a_29="";}
if($cr_lang=="en"){$lang_a_29="";}
//a30
if($cr_lang=="ar"){$lang_a_30="";}
if($cr_lang=="en"){$lang_a_30="";}
//a31
if($cr_lang=="ar"){$lang_a_31="";}
if($cr_lang=="en"){$lang_a_31="";}
//a32
if($cr_lang=="ar"){$lang_a_32="";}
if($cr_lang=="en"){$lang_a_32="";}
//a33
if($cr_lang=="ar"){$lang_a_33="";}
if($cr_lang=="en"){$lang_a_33="";}
//a34
if($cr_lang=="ar"){$lang_a_34="";}
if($cr_lang=="en"){$lang_a_34="";}
//a35
if($cr_lang=="ar"){$lang_a_35="";}
if($cr_lang=="en"){$lang_a_35="";}
//a36
if($cr_lang=="ar"){$lang_a_36="";}
if($cr_lang=="en"){$lang_a_36="";}
//a37
if($cr_lang=="ar"){$lang_a_37="";}
if($cr_lang=="en"){$lang_a_37="";}
//a38
if($cr_lang=="ar"){$lang_a_38="";}
if($cr_lang=="en"){$lang_a_38="";}
//a39
if($cr_lang=="ar"){$lang_a_39="";}
if($cr_lang=="en"){$lang_a_39="";}
//a40
if($cr_lang=="ar"){$lang_a_40="";}
if($cr_lang=="en"){$lang_a_40="";}
//a41
if($cr_lang=="ar"){$lang_a_41="";}
if($cr_lang=="en"){$lang_a_41="";}
//a42
if($cr_lang=="ar"){$lang_a_42="";}
if($cr_lang=="en"){$lang_a_42="";}
//a43
if($cr_lang=="ar"){$lang_a_43="";}
if($cr_lang=="en"){$lang_a_43="";}
//a44
if($cr_lang=="ar"){$lang_a_44="";}
if($cr_lang=="en"){$lang_a_44="";}
//a45
if($cr_lang=="ar"){$lang_a_45="";}
if($cr_lang=="en"){$lang_a_45="";}
//a46
if($cr_lang=="ar"){$lang_a_46="";}
if($cr_lang=="en"){$lang_a_46="";}
//a47
if($cr_lang=="ar"){$lang_a_47="";}
if($cr_lang=="en"){$lang_a_47="";}
//a48
if($cr_lang=="ar"){$lang_a_48="";}
if($cr_lang=="en"){$lang_a_48="";}
//a49
if($cr_lang=="ar"){$lang_a_49="";}
if($cr_lang=="en"){$lang_a_49="";}
//a50
if($cr_lang=="ar"){$lang_a_50="";}
if($cr_lang=="en"){$lang_a_50="";}
//a51
if($cr_lang=="ar"){$lang_a_51="";}
if($cr_lang=="en"){$lang_a_51="";}
//a52
if($cr_lang=="ar"){$lang_a_52="";}
if($cr_lang=="en"){$lang_a_52="";}
//a53
if($cr_lang=="ar"){$lang_a_53="";}
if($cr_lang=="en"){$lang_a_53="";}
//a54
if($cr_lang=="ar"){$lang_a_54="";}
if($cr_lang=="en"){$lang_a_54="";}
//a55
if($cr_lang=="ar"){$lang_a_55="";}
if($cr_lang=="en"){$lang_a_55="";}
//a56
if($cr_lang=="ar"){$lang_a_56="";}
if($cr_lang=="en"){$lang_a_56="";}
//a57
if($cr_lang=="ar"){$lang_a_57="";}
if($cr_lang=="en"){$lang_a_57="";}
//a58
if($cr_lang=="ar"){$lang_a_58="";}
if($cr_lang=="en"){$lang_a_58="";}
//a59
if($cr_lang=="ar"){$lang_a_59="";}
if($cr_lang=="en"){$lang_a_59="";}
//a60
if($cr_lang=="ar"){$lang_a_60="";}
if($cr_lang=="en"){$lang_a_60="";}
//a61
if($cr_lang=="ar"){$lang_a_61="";}
if($cr_lang=="en"){$lang_a_61="";}
//a62
if($cr_lang=="ar"){$lang_a_62="";}
if($cr_lang=="en"){$lang_a_62="";}
//a63
if($cr_lang=="ar"){$lang_a_63="";}
if($cr_lang=="en"){$lang_a_63="";}
//a64
if($cr_lang=="ar"){$lang_a_64="";}
if($cr_lang=="en"){$lang_a_64="";}
//a65
if($cr_lang=="ar"){$lang_a_65="";}
if($cr_lang=="en"){$lang_a_65="";}
//a66
if($cr_lang=="ar"){$lang_a_66="";}
if($cr_lang=="en"){$lang_a_66="";}
//a67
if($cr_lang=="ar"){$lang_a_67="";}
if($cr_lang=="en"){$lang_a_67="";}
//a68
if($cr_lang=="ar"){$lang_a_68="";}
if($cr_lang=="en"){$lang_a_68="";}
//a69
if($cr_lang=="ar"){$lang_a_69="";}
if($cr_lang=="en"){$lang_a_69="";}
//a70
if($cr_lang=="ar"){$lang_a_70="";}
if($cr_lang=="en"){$lang_a_70="";}
//a71
if($cr_lang=="ar"){$lang_a_71="";}
if($cr_lang=="en"){$lang_a_71="";}
//a72
if($cr_lang=="ar"){$lang_a_72="";}
if($cr_lang=="en"){$lang_a_72="";}
//a73
if($cr_lang=="ar"){$lang_a_73="";}
if($cr_lang=="en"){$lang_a_73="";}
//a74
if($cr_lang=="ar"){$lang_a_74="";}
if($cr_lang=="en"){$lang_a_74="";}
//a75
if($cr_lang=="ar"){$lang_a_75="";}
if($cr_lang=="en"){$lang_a_75="";}
//a76
if($cr_lang=="ar"){$lang_a_76="";}
if($cr_lang=="en"){$lang_a_76="";}
//a77
if($cr_lang=="ar"){$lang_a_77="";}
if($cr_lang=="en"){$lang_a_77="";}
//a78
if($cr_lang=="ar"){$lang_a_78="";}
if($cr_lang=="en"){$lang_a_78="";}
//a79
if($cr_lang=="ar"){$lang_a_79="";}
if($cr_lang=="en"){$lang_a_79="";}
//a80
if($cr_lang=="ar"){$lang_a_80="";}
if($cr_lang=="en"){$lang_a_80="";}
//a81
if($cr_lang=="ar"){$lang_a_81="";}
if($cr_lang=="en"){$lang_a_81="";}
//a82
if($cr_lang=="ar"){$lang_a_82="";}
if($cr_lang=="en"){$lang_a_82="";}
//a83
if($cr_lang=="ar"){$lang_a_83="";}
if($cr_lang=="en"){$lang_a_83="";}
//a84
if($cr_lang=="ar"){$lang_a_84="";}
if($cr_lang=="en"){$lang_a_84="";}
//a85
if($cr_lang=="ar"){$lang_a_85="";}
if($cr_lang=="en"){$lang_a_85="";}
//a86
if($cr_lang=="ar"){$lang_a_86="";}
if($cr_lang=="en"){$lang_a_86="";}
//a87
if($cr_lang=="ar"){$lang_a_87="";}
if($cr_lang=="en"){$lang_a_87="";}
//a88
if($cr_lang=="ar"){$lang_a_88="";}
if($cr_lang=="en"){$lang_a_88="";}
//a89
if($cr_lang=="ar"){$lang_a_89="";}
if($cr_lang=="en"){$lang_a_89="";}
//a90
if($cr_lang=="ar"){$lang_a_90="";}
if($cr_lang=="en"){$lang_a_90="";}
//a91
if($cr_lang=="ar"){$lang_a_91="";}
if($cr_lang=="en"){$lang_a_91="";}
//a92
if($cr_lang=="ar"){$lang_a_92="";}
if($cr_lang=="en"){$lang_a_92="";}
//a93
if($cr_lang=="ar"){$lang_a_93="";}
if($cr_lang=="en"){$lang_a_93="";}
//a94
if($cr_lang=="ar"){$lang_a_94="";}
if($cr_lang=="en"){$lang_a_94="";}
//a95
if($cr_lang=="ar"){$lang_a_95="";}
if($cr_lang=="en"){$lang_a_95="";}
//a96
if($cr_lang=="ar"){$lang_a_96="";}
if($cr_lang=="en"){$lang_a_96="";}
//a97
if($cr_lang=="ar"){$lang_a_97="";}
if($cr_lang=="en"){$lang_a_97="";}
//a98
if($cr_lang=="ar"){$lang_a_98="";}
if($cr_lang=="en"){$lang_a_98="";}
//a99
if($cr_lang=="ar"){$lang_a_99="";}
if($cr_lang=="en"){$lang_a_99="";}
//a100
if($cr_lang=="ar"){$lang_a_100="";}
if($cr_lang=="en"){$lang_a_100="";}
*/
?>